# Generated by Django 5.2.4 on 2025-07-16 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_contactoproveedor_proveedorempresa_unidadmedida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmodelo',
            name='marca',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Marca - modelo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.marca', verbose_name='Marca asociada'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(help_text='Marca - modelo', on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='inventario.marca', verbose_name='Marca asociada'),
        ),
    ]
