# Generated by Django 6.0.6 on 2026-06-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0002_venta"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Venta",
        ),
    ]
