# Generated by Django 5.2.4 on 2025-07-16 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_historicalmodelo_marca_alter_modelo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='modelo',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Marca - modelo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inventario.modelo', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.ForeignKey(help_text='Marca - modelo', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.modelo', verbose_name='Modelo'),
        ),
    ]
