# Generated by Django 5.2.4 on 2025-07-22 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_contactoproveedor_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducto',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('DESCONTINUADO', 'Descontinuado'), ('PEDIDO_ESPECIAL', 'Pedido especial'), ('Proximo a gotarse', 'proximo')], default='DISPONIBLE', max_length=30, verbose_name='Estado del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('AGOTADO', 'Agotado'), ('DESCONTINUADO', 'Descontinuado'), ('PEDIDO_ESPECIAL', 'Pedido especial'), ('Proximo a gotarse', 'proximo')], default='DISPONIBLE', max_length=30, verbose_name='Estado del producto'),
        ),
    ]
