# Generated by Django 6.0.6 on 2026-06-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0005_detalleventa"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="estado",
            field=models.CharField(default="activa", max_length=20),
        ),
    ]
