# Generated by Django 5.2.4 on 2026-03-04 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_historicalproducto_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriaproducto',
            name='nombre',
            field=models.CharField(max_length=60, unique=True, verbose_name='Nombre de categoría'),
        ),
        migrations.AlterField(
            model_name='historicalcategoriaproducto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=60, verbose_name='Nombre de categoría'),
        ),
    ]
