# Generated by Django 6.0.6 on 2026-06-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0006_venta_estado"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_empresa", models.CharField(max_length=100)),
                ("telefono", models.CharField(blank=True, max_length=50, null=True)),
                ("correo", models.EmailField(max_length=100, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                (
                    "mensaje_final",
                    models.CharField(
                        default="Gracias por su compra, vuelva pronto.", max_length=255
                    ),
                ),
            ],
        ),
    ]
