# Generated by Django 6.0.6 on 2026-07-12 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0009_venta_cierre"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SALIDA", "Salida")],
                        max_length=10,
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("COMPRA", "Compra a proveedor"),
                            ("DEVOLUCION_CLIENTE", "Devolución de cliente"),
                            ("DEVOLUCION_PROVEEDOR", "Devolución a proveedor"),
                            ("MERMA", "Merma / Daño"),
                            ("AJUSTE", "Ajuste de inventario"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=30,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="inventario.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
