# Generated by Django 6.0.6 on 2026-07-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0012_movimientocredito_cancelado"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientocredito",
            name="productos_json",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
