# Generated by Django 6.0.6 on 2026-08-03 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0014_remove_venta_cierre_venta_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="cierre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ventas",
                to="inventario.cierrecaja",
            ),
        ),
    ]
