# Generated by Django 6.0.6 on 2026-08-03 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0015_venta_cierre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientocredito",
            name="concepto",
            field=models.TextField(blank=True, help_text="Ej. 'Filtro aire.'"),
        ),
    ]
