from .categoriaProducto_admin import CategoriaProductoAdmin
from .marca_admin import MarcaProductoAdmin
from .unidadMedida_admin import UnidadMedidaAdmin

from .contactoProveedor_admin import ContactoProveedorAdmin
from .producto_admin import ProductoAdmin
from .productoImagen_admin import ProductoImagenAdmin
from .proveedorEmpresa_admin import ProveedorEmpresaAdmin

from .venta_admin import VentaAdmin
from .detalleVenta_admin import DetalleVentaAdmin
from .configuracionTicket_admin import ConfiguracionTicketAdmin