from .categoriaProducto_admin import CategoriaProductoAdmin
from .marca_admin import MarcaProductoAdmin
from .unidadMedida_admin import UnidadMedidaAdmin

from .contactoProvedor_admin import ContactoProveedorAdmin
from .producto_admin import ProductoAdmin
from .productoImagen_admin import ProductoImagenAdmin
from .provedorEmpresa_admin import ProveedorEmpresaAdmin