from .dashboard_Views import *
from .producto_Views import *
from .proveedor_Views import *
from .categoriaProducto_Views import *
from .marcaProducto_Views import *
from .contactoProveedor_Views import *
from .ventas_Views import *
from .ticket_Views import *
from .inventarioMovimientos_Views import *
from .kardex_Views import *
